----use run script (f5) not run statement
spool '/USERS/AAMACDON/DESKTOP/ddlGenerator.sql';
SELECT DBMS_METADATA.GET_DDL('TABLE', 'HUBEVENTCHECKIN') FROM USER_TABLES;
SELECT DBMS_METADATA.GET_DDL('TABLE', 'HUBEVENTS') FROM USER_TABLES;
SELECT DBMS_METADATA.GET_DDL('TABLE', 'HUBHUBSTERS') FROM USER_TABLES;
SELECT DBMS_METADATA.GET_DDL('TABLE', 'HUBMANAGERS') FROM USER_TABLES;
SELECT DBMS_METADATA.GET_DDL('TABLE', 'HUBPILLARS') FROM USER_TABLES;
SELECT DBMS_METADATA.GET_DDL('TABLE', 'HUBROLES') FROM USER_TABLES;
SELECT DBMS_METADATA.GET_DDL('TABLE', 'HUBROOMS') FROM USER_TABLES;
select dbms_metadata.get_ddl('PROCEDURE', 'CREATEEVENT') from dual;
select dbms_metadata.get_ddl('PROCEDURE', 'EVENTCHECKIN') from dual;
select dbms_metadata.get_ddl('PROCEDURE', 'INSERTHUBSTER') from dual;
select dbms_metadata.get_ddl('PROCEDURE', 'INSERTPILLAR') from dual;
select dbms_metadata.get_ddl('PROCEDURE', 'UPDATEHUBSTER') from dual;
select dbms_metadata.get_ddl('PROCEDURE', 'UPDATEMANAGER') from dual;
spool off;

